Remove github action extra stuff to test with fewer steps

diff --git a/.github/workflows/validate-meta-info-file.yml b/.github/workflows/validate-meta-info-file.yml
--- a/.github/workflows/validate-meta-info-file.yml
+++ b/.github/workflows/validate-meta-info-file.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - main
 
-permissions: write-all
+#permissions: write-all
 
 jobs:
   run:
@@ -27,32 +27,33 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run validate command
-        run: python manage.py validatemetainfofile | tee validate_output.txt
-      - name: Read output file
-        id: validate_output
-        uses: juliangruber/read-file-action@v1
-        with:
-          path: ./validate_output.txt
-      - name: Comment on pull request
-        uses: thollander/actions-comment-pull-request@main
-        if: "${{ contains(steps.validate_output.outputs.content, 'errors found') }}"
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          message: '**Validate Language Files**
-
-Output:
-
-${{ steps.validate_output.outputs.content }}
-
-
-If the output is blank, all checks passed.
-
-If there are errors, you should fix those before the PR will pass.
-
-If there are warnings, those are optional and you should consider whether to change them or not.
-'
-
-      - name: Check for command failures
-        if: "${{ contains(steps.validate_output.outputs.content, 'errors found') }}"
-        run: |
-          exit 1
+        run: python manage.py validatemetainfofile
+#        run: python manage.py validatemetainfofile | tee validate_output.txt
+#      - name: Read output file
+#        id: validate_output
+#        uses: juliangruber/read-file-action@v1
+#        with:
+#          path: ./validate_output.txt
+#      - name: Comment on pull request
+#        uses: thollander/actions-comment-pull-request@main
+#        if: "${{ contains(steps.validate_output.outputs.content, 'errors found') }}"
+#        with:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          message: '**Validate Language Files**
+#
+#Output:
+#
+#${{ steps.validate_output.outputs.content }}
+#
+#
+#If the output is blank, all checks passed.
+#
+#If there are errors, you should fix those before the PR will pass.
+#
+#If there are warnings, those are optional and you should consider whether to change them or not.
+#'
+#
+#      - name: Check for command failures
+#        if: "${{ contains(steps.validate_output.outputs.content, 'errors found') }}"
+#        run: |
+#          exit 1
